/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package IU_Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author renna
 */
public class InterfaceGrafica extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGrafica
     */
    public InterfaceGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        RemoverAluno = new javax.swing.JMenuItem();
        RemoverTurma = new javax.swing.JMenuItem();
        RemoverDisciplina = new javax.swing.JMenuItem();
        RemoverDeTurma = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem25.setText("jMenuItem25");

        jMenuItem26.setText("jMenuItem26");

        jMenuItem27.setText("jMenuItem27");

        jMenuItem28.setText("jMenuItem28");

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setForeground(new java.awt.Color(62, 67, 76));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IU_Sistema/img/eagle.png"))); // NOI18N

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 285, Short.MAX_VALUE))
        );

        jMenu1.setText("Cadastro");

        jMenuItem5.setText("Aluno");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroAluno(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Turma");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroTurmas(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Disciplina");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroDisciplinas(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setText("Avaliação");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAvaliacao(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem9.setText("Alunos em Turma");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarAlunosEmTurma(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Buscar");

        jMenuItem10.setText("Aluno");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarAluno(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Disciplina");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarDisciplina(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Turma");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarTurma(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Avaliação ");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarAvaliacao(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setText("Alunos de Turma");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarAlunosDaTurma(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setText("Avaliações por Aluno");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarAvaliacoesDoAluno(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuItem16.setText("Avaliações por Turma");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarAvaliacaoPorTurma(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Listar");

        jMenuItem17.setText("Turmas");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTurma(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jMenuItem18.setText("Alunos");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarAlunos(evt);
            }
        });
        jMenu3.add(jMenuItem18);

        jMenuItem19.setText("Disciplinas");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarDisciplinas(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuItem20.setText("Avaliações");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarAvaliacoes(evt);
            }
        });
        jMenu3.add(jMenuItem20);

        jMenuItem21.setText("Turmas por aluno");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTurmasPorAluno(evt);
            }
        });
        jMenu3.add(jMenuItem21);

        jMenuItem22.setText("Turmas por disciplina");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarTurmasPorDisciplina(evt);
            }
        });
        jMenu3.add(jMenuItem22);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");

        jMenuItem23.setText("Por Turma");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioPorTurma(evt);
            }
        });
        jMenu4.add(jMenuItem23);

        jMenuItem24.setText("Por Disciplina");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioPorDisciplina(evt);
            }
        });
        jMenu4.add(jMenuItem24);

        jMenuBar1.add(jMenu4);

        jMenu9.setText("Remover");

        RemoverAluno.setText("Aluno");
        RemoverAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverAlunoActionPerformed(evt);
            }
        });
        jMenu9.add(RemoverAluno);

        RemoverTurma.setText("Turma");
        RemoverTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverTurmaActionPerformed(evt);
            }
        });
        jMenu9.add(RemoverTurma);

        RemoverDisciplina.setText("Disciplina");
        RemoverDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverDisciplinaActionPerformed(evt);
            }
        });
        jMenu9.add(RemoverDisciplina);

        RemoverDeTurma.setText("Alunos de Turma");
        RemoverDeTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverDeTurmaActionPerformed(evt);
            }
        });
        jMenu9.add(RemoverDeTurma);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 325, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Cadastro Aluno
    private void CadastroAluno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroAluno
        IU_CadastroAlunos iuCadastroAluno = new IU_CadastroAlunos();
        jDesktopPane1.add(iuCadastroAluno);
        iuCadastroAluno.setVisible(true);
    }//GEN-LAST:event_CadastroAluno
    
    //Cadastro avaliação
    private void CadastrarAvaliacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAvaliacao
        IU_CadastroAvaliacao iu = new IU_CadastroAvaliacao();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_CadastrarAvaliacao
    
    //Cadastro Turma
    private void CadastroTurmas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroTurmas
        IU_CadastroTurma iuCadastrarTurma = new IU_CadastroTurma();
        jDesktopPane1.add(iuCadastrarTurma);
        iuCadastrarTurma.setVisible(true);
    }//GEN-LAST:event_CadastroTurmas
    
    //Cadastro Disciplina
    private void CadastroDisciplinas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroDisciplinas
        IU_CadastroDisciplina iu = new IU_CadastroDisciplina();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_CadastroDisciplinas
    
    //Cadastrar Alunos em Turma
    private void CadastrarAlunosEmTurma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarAlunosEmTurma
        IU_CadastroAlunosEmTurma iu = new IU_CadastroAlunosEmTurma();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_CadastrarAlunosEmTurma

    private void BuscarDisciplina(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarDisciplina
        IU_BuscaDisciplina iu = new IU_BuscaDisciplina();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_BuscarDisciplina

    private void BuscarAluno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarAluno
        IU_BuscaAluno iu = new IU_BuscaAluno();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_BuscarAluno

    private void BuscarTurma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarTurma
        IU_BuscaTurma iu = new IU_BuscaTurma();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_BuscarTurma

    private void BuscarAvaliacao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarAvaliacao
        IU_BuscaAvaliacao iu = new IU_BuscaAvaliacao();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_BuscarAvaliacao

    private void BuscarAlunosDaTurma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarAlunosDaTurma
        IU_BuscaAlunosTurma iu = new IU_BuscaAlunosTurma();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_BuscarAlunosDaTurma

    private void BuscarAvaliacoesDoAluno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarAvaliacoesDoAluno
        IU_BuscarAvaliacoesPorAluno iu = new IU_BuscarAvaliacoesPorAluno();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_BuscarAvaliacoesDoAluno

    private void BuscarAvaliacaoPorTurma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarAvaliacaoPorTurma
        IU_BuscaAvaliacoesPorTurma iu = new IU_BuscaAvaliacoesPorTurma();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_BuscarAvaliacaoPorTurma

    private void ListarAlunos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarAlunos
        IU_ListarAlunos iu = new IU_ListarAlunos();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_ListarAlunos

    private void ListarTurma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTurma
        IU_ListarTurmas iu = new IU_ListarTurmas();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_ListarTurma

    private void ListarDisciplinas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarDisciplinas
        IU_LIstarDisciplinas iu = new IU_LIstarDisciplinas();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_ListarDisciplinas

    private void ListarAvaliacoes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarAvaliacoes
        IU_ListarAvaliacoes iu = new IU_ListarAvaliacoes();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_ListarAvaliacoes

    private void ListarTurmasPorAluno(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTurmasPorAluno
        IU_ListarTurmasPorAluno iu = new IU_ListarTurmasPorAluno();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_ListarTurmasPorAluno

    private void ListarTurmasPorDisciplina(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarTurmasPorDisciplina
        IU_ListarTurmasPorDisciplina iu = new IU_ListarTurmasPorDisciplina();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_ListarTurmasPorDisciplina

    private void RelatorioPorDisciplina(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioPorDisciplina
        IU_RelatorioDisciplina iu = new IU_RelatorioDisciplina();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_RelatorioPorDisciplina

    private void RelatorioPorTurma(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioPorTurma
        IU_RelatorioTurma iu = new IU_RelatorioTurma();
        jDesktopPane1.add(iu);
        iu.setVisible(true);
    }//GEN-LAST:event_RelatorioPorTurma

    private void RemoverAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverAlunoActionPerformed
        JOptionPane.showMessageDialog(this, 
        "Função em desenvolvimento!\nDisponível em um próximo ciclo 😄", 
        "Indisponível", 
        JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:
    }//GEN-LAST:event_RemoverAlunoActionPerformed

    private void RemoverTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverTurmaActionPerformed
        JOptionPane.showMessageDialog(this, 
        "Função em desenvolvimento!\nDisponível em um próximo ciclo 😄", 
        "Indisponível", 
        JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:
    }//GEN-LAST:event_RemoverTurmaActionPerformed

    private void RemoverDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverDisciplinaActionPerformed
        JOptionPane.showMessageDialog(this, 
        "Função em desenvolvimento!\nDisponível em um próximo ciclo 😄", 
        "Indisponível", 
        JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:
    }//GEN-LAST:event_RemoverDisciplinaActionPerformed

    private void RemoverDeTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverDeTurmaActionPerformed
       JOptionPane.showMessageDialog(this, 
        "Função em desenvolvimento!\nDisponível em um próximo ciclo 😄", 
        "Indisponível", 
        JOptionPane.INFORMATION_MESSAGE);// TODO add your handling code here:
    }//GEN-LAST:event_RemoverDeTurmaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem RemoverAluno;
    private javax.swing.JMenuItem RemoverDeTurma;
    private javax.swing.JMenuItem RemoverDisciplina;
    private javax.swing.JMenuItem RemoverTurma;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
